### ISSUE TITLE
EF Core support

### ISSUE THREAD

**Issue by Dedigraz** [fauna/faunadb-csharp#127]
I would like to know whether there would ever be a faunadb extension for EFcore since it's one of the main ways that people manipulate databases in .Net

**Comment by n400** [comment]
Hi @Dedigraz, this is something we've discussed putting on our roadmap in the future. Please feel free to post this request in our Forums' "feature request" category https://forums.fauna.com/c/feature-requests/2

**Comment by Texnomic** [comment]
We need an update on this issue since the current state of this library requires a lot of abstraction and extensions to make more C# developer friendly compared to other ORM solutions.

I'm currently working on an EFCore-like abstraction above the existing library but after intensive experience with it, I can confirm that this library is very difficult it work with because of its syntax being very alienating to even advanced C# developer.

Btw, I love fauna, and I want to adopt it everywhere!
