### ISSUE TITLE
Package FaunaDB.Client 1.1.0 is not compatible with netcoreapp1.1

### ISSUE THREAD

**Issue by Thaina** [fauna/faunadb-csharp#61]
> Package FaunaDB.Client 1.1.0 is not compatible with netcoreapp1.1 (.NETCoreApp,Version=v1.1). Package FaunaDB.Client 1.1.0 supports: net45 (.NETFramework,Version=v4.5)

Please add support to dotnet core. It was used in modern platform and especially Amazon Lambda

**Comment by marrony** [comment]
@Thaina I know you asked to support for `netcoreapp1.1` however our driver uses some reflections under the hood in order to improve the performance for user defined types, mainly `System.Type` has a lot of missing methods and properties in that version, so I could only make the driver works on `netcoreapp2.0` as well as `net45;net46;net47`. Does that version works for you? I saw AWS Lambda now supports [.net core 2.0](https://aws.amazon.com/about-aws/whats-new/2018/01/aws-lambda-supports-c-sharp-dot-net-core-2-0/)

here is the PR https://github.com/fauna/faunadb-csharp/pull/62 case you're curious, feel free to give feedback as well

**Comment by Thaina** [comment]
Yes, just core 2.0 is perfectly fine

**Comment by marrony** [comment]
would you mind to test this prerelease and see if it works?
https://www.nuget.org/packages/FaunaDB.Client/1.2.1-alpha
